### ISSUE TITLE
[sc-text] don't have font-size css propriety

### ISSUE THREAD

**Issue by etiennedemoulin** [ircam-ismm/sc-components#1]
sc-text {
  font-size: 30px;
}  
font-size property is not working

**Comment by b-ma** [comment]
Yup it behaves quite weirdly... 

But more generally I'm not very happy with this component, it is not clean and its main usage is rather ill-defined I think...

I think we should reverse the behaviour so that it behaves more like the Max comment box: readonly by default / editable on demand (as we have the `sc-editor` for proper code editing needs):

```js
<sc-text>My label</sc-text>
```

```js
<sc-text
  editable
  // triggered on blur and/or Cmd+S
  @change=${e => console.log(e.detail.value}
>My default value</sc-text>
```

What do you think?

**Comment by etiennedemoulin** [comment]
Sounds great !
